#!/bin/bash

SANDBOX_TOTAL_TIMEOUT=3000
SANDBOX_CPU_LIMIT=1000
SANDBOX_MEMORY_LIMIT=10000000
SANDBOX_STDOUT_LIMIT=-1
SANDBOX_STDERR_LIMIT=-1
INPUT_FILE=/tmp/tests/$APP/$LANG/$TEST.in

mkdir -p $(dirname $INPUT_FILE)
dd status=none if=/dev/zero of=$INPUT_FILE bs=1M count=10
