#!/bin/bash

export SANDBOX_TOTAL_TIMEOUT=1000
export SANDBOX_CPU_LIMIT=1000
export SANDBOX_MEMORY_LIMIT=15728640
export SANDBOX_STDOUT_LIMIT=-1
export SANDBOX_STDERR_LIMIT=-1
export INPUT_FILE=/dev/null
