#!/bin/bash

export SANDBOX_TOTAL_TIMEOUT=3000
export SANDBOX_CPU_LIMIT=2000
export SANDBOX_MEMORY_LIMIT=10485760
export SANDBOX_STDOUT_LIMIT=100
export SANDBOX_STDERR_LIMIT=500
export INPUT_FILE=/tests/$APP/$LANG/$TEST.in
