#!/bin/bash

. $1

export SANDBOX_USER=sandbox
export SANDBOX_USER_UID=1888
export SANDBOX_USER_GID=1888

export SANDBOX_CPU_LIMIT_ADDITION=2000
export SANDBOX_THREAD_COUNT_LIMIT=100
export SANDBOX_FILE_SIZE_LIMIT=0
export SANDBOX_OPEN_FILE_LIMIT=500
export SANDBOX_CHILDREN_FORBIDDEN=1
export SANDBOX_VERBOSE=0
export SANDBOX_SYSLOG=1

groupadd --gid $SANDBOX_USER_GID $SANDBOX_USER \
    && useradd --uid $SANDBOX_USER_UID --gid $SANDBOX_USER_GID -m $SANDBOX_USER

sandbox $WORKING_DIR/$TEST.stat $WORKING_DIR $TEST_EXE < $INPUT_FILE 1> $WORKING_DIR/$TEST.out 2> $WORKING_DIR/$TEST.err

ps axww --format=pid,ppid,pgid,sid,stat,command > $WORKING_DIR/$TEST.proc
